/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_midnightas_jgetch_JGetch */

#ifndef _Included_org_midnightas_jgetch_JGetch
#define _Included_org_midnightas_jgetch_JGetch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_midnightas_jgetch_JGetch
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_midnightas_jgetch_JGetch_getch
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
